#ifndef HAP_DEFS_HPP
#define HAP_DEFS_HPP

// Accessory Categories
#define HAP_CAT_OTHER 1
#define HAP_CAT_BRIDGE 2
#define HAP_CAT_FAN 3
#define HAP_CAT_GARAGE 4
#define HAP_CAT_LIGHTBULB 5
#define HAP_CAT_DOOR_LOCK 6
#define HAP_CAT_OUTLET 7
#define HAP_CAT_SWITCH 8
#define HAP_CAT_THERMOSTAT 9
#define HAP_CAT_SENSOR 10
#define HAP_CAT_SECURITY_SYSTEM 11
#define HAP_CAT_DOOR 12
#define HAP_CAT_WINDOW 13
#define HAP_CAT_WINDOW_COVERING 14
#define HAP_CAT_PROGRAMMABLE_SWITCH 15
#define HAP_CAT_RANGE_EXTENDER 16
#define HAP_CAT_IP_CAMERA 17
#define HAP_CAT_VIDEO_DOOR_BELL 18
#define HAP_CAT_AIR_PURIFIER 19

// TVL METHODS
#define HAP_TLV_METHOD_PAIR_SETUP 1
#define HAP_TLV_METHOD_PAIR_VERIFY 2
#define HAP_TLV_METHOD_ADD_PAIRING 3
#define HAD_TLV_METHOD_REMOVE_PAIRING 4
#define HAP_TLV_METHOD_LIST_PAIRINGS 5

// TLV Errors
#define HAP_TLV_ERROR_UNKOWN 0x01
#define HAP_TLV_ERROR_AUTH 0x02
#define HAP_TLV_ERROR_BACKOFF 0x03
#define HAP_TLV_ERROR_MAX_PEERS 0x04
#define HAP_TLV_ERROR_MAX_TRIES 0x05
#define HAP_TLV_ERROR_UNAVAILABLE 0x06
#define HAP_TLV_ERROR_BUSY 0x07

// TLV Types
#define HAP_TLV_TYPE_METHOD 0x00
#define HAP_TLV_TYPE_IDENTIFIER 0x01
#define HAP_TLV_TYPE_SALT 0x02
#define HAP_TLV_TYPE_PUB_KEY 0x03
#define HAP_TLV_TYPE_PROOF 0x04
#define HAP_TLV_TYPE_ENCRYPTED_DATA 0x05
#define HAP_TLV_TYPE_STATE 0x06
#define HAP_TLV_TYPE_ERROR 0x07
#define HAP_TLV_TYPE_RETRY_DELAY 0x08
#define HAP_TLV_TYPE_CERT 0x09
#define HAP_TLV_TYPE_SIGNATURE 0x0A
#define HAP_TLV_TYPE_PERMS 0x0B
#define HAP_TLV_TYPE_FRAGMENT_DATA 0x0C
#define HAP_TLV_TYPE_FRAGMENT_LAST 0x0D
#define HAP_TLV_TYPE_SEPARATOR 0xFF

// Apple Defined Services
#define APPL_SRVC_UUID_BASE "0000-1000-8000-0026BB765291"

#define APPL_SRVC_UUID_ACCESSORY_INFO 0x3E
#define APPL_SRVC_UUID_FAN 0x40
#define APPL_SRVC_UUID_GARAGE_DOOR_OPENER 0x41
#define APPL_SRVC_UUID_LIGHTBULB 0x43
#define APPL_SRVC_UUID_LOCK_MANAGEMENT 0x44
#define APPL_SRVC_UUID_LOCK_MECHANISM 0x45
#define APPL_SRVC_UUID_OUTLET 0x47
#define APPL_SRVC_UUID_SWITCH 0x49
#define APPL_SRVC_UUID_THERMOSTAT 0x41
#define APPL_SRVC_UUID_AIR_QUALITY_SENSOR 0x8D
#define APPL_SRVC_UUID_SECUIRTY_SYSTEM 0x7E
#define APPL_SRVC_UUID_CARBON_MONOXIDE_SENSOR 0x7F


#endif // HAP_DEFS_HPP
